log_file: ./log.txt
syscalls:
    - umount2:
        log: true
        block: true
        arg0: "/usr"
        arg0_char: true
        arg1: 1
        arg1_char: false
    - umount2:
        log: false
        block: true
        arg0: "/home/xen/Projects/syscall-interceptor/test"
        arg0_char: true
        arg1: 2
        arg1_char: false
    - getdents64:
        log: true
        block: false
